name: PyFunceble Dev Workflow
on:
  pull_request:
    branches:
      - dev
      - 4.0.0-dev
      - test-github-actions
  push:
    branches:
      - dev
      - 4.0.0-dev
      - test-github-actions
  schedule:
    - cron: "0 0 * * *"

jobs:
  lint:
    name: Lint PyFunceble with Python ${{ matrix.python_version }} under ${{ matrix.os }}

    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.9.1"
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Clone repository

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pylint

      - name: Lint PyFunceble with Pylint
        run: pylint PyFunceble

      - name: Lint tests with Pylint
        run: pylint tests

  test:
    needs: lint
    name: "[${{ matrix.os }}] Test PyFunceble with Python ${{ matrix.python_version }}"

    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.7.9"
          - "3.8.6"
          - "3.9.1"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v2
        name: Clone repository

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install tox coveralls

      - name: Test PyFunceble as defined by tox.ini
        run: |
          tox -c tox.ini

      - name: Upload Coverage
        run: |
          coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          COVERALLS_PARALLEL: true

  coveralls:
    needs: test
    name: Finish Coveralls

    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.9.1"
        os:
          - ubuntu-latest

    steps:
      - name: Sending finish flag to coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true

  run_cli:
    needs: test
    name: "[${{ matrix.os }}] Run PyFunceble with Python ${{ matrix.python_version }}"

    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.7.9"
          - "3.8.6"
          - "3.9.1"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v2
        name: Clone repository

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install tox

      - name: Run PyFunceble as defined by tox_run.ini
        run: tox -c tox_run.ini

  run_cli_mariadb:
    needs: test
    name: "[${{ matrix.os }}] Run PyFunceble (with mariadb) with Python ${{ matrix.python_version }}"

    runs-on: "${{ matrix.os }}"

    services:
      mariadb:
        image: ghcr.io/pyfunceble/mariadb/mariadb:latest
        ports:
          - 3306:3306
        env:
          MYSQL_USER: pyfunceble
          MYSQL_PASSWORD: my_pyfunceble_password
          MYSQL_DATABASE: pyfunceble
          MYSQL_ROOT_PASSWORD: my_awesome_root_password
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    env:
      PYFUNCEBLE_DB_CHARSET: utf8mb4
      PYFUNCEBLE_DB_HOST: "127.0.0.1"
      PYFUNCEBLE_DB_NAME: pyfunceble
      PYFUNCEBLE_DB_PASSWORD: my_pyfunceble_password
      PYFUNCEBLE_DB_PORT: "3306"
      PYFUNCEBLE_DB_USERNAME: pyfunceble

    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.7.9"
          - "3.8.6"
          - "3.9.1"
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Clone repository

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install tox

      - name: Run PyFunceble as defined by tox_run_mariadb.ini
        run: tox -c tox_run_mariadb.ini
